project:
  type: website

website:
  title: "Edwin Leck | Business Analytics & Software Engineering"
  navbar:
    left:
      - about.qmd
      - projects.qmd
      - cv.qmd
      - contact.qmd
  page-footer:
    center: "© 2025 Edwin Leck. All rights reserved."

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
